### ISSUE TITLE
check idiom name and type for "maps&data" pages

### ISSUE THREAD

**Issue by sverhees** [agricolamz/tald_gm#11]
We need a test for the name and type of idiom in feature datasets for the map pages.

Sometimes contributors make typos in the names of idioms, or they write Verkhnee Gakvari instead of Upper Gakvari, and sometimes they use the wrong classification (e.g. dialect_toplevel when it's actually dialect_nt1).

So we would need a test that checks whether the idiom name (column: **idiom**) is present within the type category they use, if not, it should check whether the name is present in any of the other categories. In the outcome we need a list with wrong classifications (for example "idiom name X is not in column dialect_toplevel"), and a list with "non-existing" idiom names.

For comparison you need the TALD version of the villages dataset.

**Comment by agricolamz** [comment]
I'm currently working on it. Why then ask people to provide _type_ information since we have a more than strong opinion on it?

**Comment by sverhees** [comment]
All they have to do is choose the right one and copy it.

But sometimes idiom names exist on two levels, e.g. there are 9 villages where the Kidero dialect of Tsez is spoken, but there is also a village called Kidero. A source could have checked multiple villages and claim that they describe the dialect, or they may provide data specifically from the village Kidero. Sometimes there is different info in one source.

We do not (always) know a priori which information contributors retrieved from the source, so they have to pick the right type themselves. But sometimes they make mistakes and assign a type that is not at all associated with the particular idiom name.

**Comment by agricolamz** [comment]
Got it! Thanks!

[Here](https://github.com/agricolamz/tald_gm/runs/5002533525?check_suite_focus=true) will be some results. It not in the format that you want. It states:

```
The wrong village dialect name Lower Gakvari in the file distance_contrasts.tsv
```

So after it user need to decide, whether it is a typo or wrong category.

**Comment by sverhees** [comment]
Thanks!

So based on what does it decide that a name is wrong?

**Comment by agricolamz** [comment]
I used the `tald_villages.csv` that you've sent me. It is in the `data` folder. So for example you can make a fork and change it. I'm not sure about `Eastern Armenian` that for some reason is absent in the `tald_villages.csv`.

**Comment by sverhees** [comment]
I was asking more specifically about the process.
Do I understand correctly that it is wrong if there is no idiom with such a
name in the type it was assigned? So I have to check manually whether there
is a typo or a wrong classification?

Eastern Armenian should be Modern Eastern Armenian.
But strangely both are wrong in the test :). I will look into this.

**Comment by agricolamz** [comment]
I fixed Modern Eastern Armenian and now it is gone.

https://github.com/agricolamz/tald_gm/runs/5005013766?check_suite_focus=true#step:9:83

**Comment by sverhees** [comment]
<3
