### ISSUE TITLE
get missing arguments in biblib

### ISSUE THREAD

**Issue by chnaccarato** [agricolamz/tald_gm#7]
we need to get a list of missing (obligatory) arguments for the entries in the biblib table

**Comment by agricolamz** [comment]
@chnaccarato, can you eloborate, how to figure out which of them are obligatory...

**Comment by chnaccarato** [comment]
@agricolamz different arguments are obligatory for different entry types: https://www.bibtex.com/e/entry-types/
do you need a list of arguments for each entry type in some format different from that available at the link above?
